### ISSUE TITLE
Custom dataset

### ISSUE THREAD

**Issue by MaleshwarSastri** [WenbinLee/CovaMNet#2]
HI,
I am working on my custom logo detection dataset.Can you guide me on how to train and test(detection) my model.Mainly im not able to understand the detection part.Kindly provide more details,also mention on how to use 5 shot algorithm

**Comment by WenbinLee** [comment]
Hi, thanks for interesting in our work.
Because our code is specifically designed  for image classification, it's a little different from the detection task. I think maybe you can replace the classifier module of our model with a detection module. Hope this can help you.
