### ISSUE TITLE
准确率问题

### ISSUE THREAD

**Issue by linezp** [WenbinLee/CovaMNet#4]
您好，我在本地测试了代码的结果，发现在miniImageNet数据集上准确率相当，但在stand_dog和Cub_bird数据集上测试出来的准确率相较于论文中要差3%-4%，是否是超参对结果有影响呢，还是我多重复跑几次可能会有更好的结果？
麻烦您了

**Comment by linezp** [comment]
还会出现一个奇怪的现象，dog数据集训练时val的准确率要高test准确率4%，不知道您有没有遇到过这种问题。

**Comment by WenbinLee** [comment]
您好，在dog和bird数据集上是否存在严重的过拟合现象呢？
验证集结果和测试集结果的差异可能是固定BN造成的，您看看是否可以把CovaMNet_Train_5way1shot.py 里386行的model.eval() 换成model.train()，看看新的结果如何。

另外，由于dog和bird数据比较少，可能比较容易过拟合，其实应该做一下数据增广。
